name: nakster_pro
description: Nakster Pro ERP v2.0 - Arabic offline accounting and inventory system.
publish_to: none
version: 2.0.0+2
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.8.3
  flutter_barcode_scanner: ^2.0.0
  pdf: ^3.10.7
  printing: ^5.11.1
  intl: ^0.19.0
  fl_chart: ^0.68.0
  file_picker: ^8.0.0
  share_plus: ^7.2.2
  image_picker: ^1.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/Cairo-Regular.ttf
