import 'package:path/path.dart';
import 'package:sqflite/sqflite.dart';

class DatabaseHelper {
  DatabaseHelper._();
  static final instance = DatabaseHelper._();
  Database? _db;
  Future<Database> get database async => _db ??= await _open();

  Future<Database> _open() async {
    final file = join(await getDatabasesPath(), 'nakster_pro_v2.db');
    return openDatabase(file, version: 1, onCreate: (db, version) async {
      await db.execute('CREATE TABLE products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,barcode TEXT DEFAULT \'\',price REAL DEFAULT 0,cost REAL DEFAULT 0,quantity REAL DEFAULT 0,type TEXT DEFAULT \'عادي\',unit TEXT DEFAULT \'قطعة\',serial TEXT DEFAULT \'\',expiry TEXT DEFAULT \'\',image TEXT DEFAULT \'\',purchase_price REAL DEFAULT 0,sale_price REAL DEFAULT 0,created_at TEXT DEFAULT \'\')');
      await db.execute('CREATE TABLE customers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT DEFAULT \'\',balance REAL DEFAULT 0,address TEXT DEFAULT \'\',created_at TEXT DEFAULT \'\')');
      await db.execute('CREATE TABLE invoices(id INTEGER PRIMARY KEY AUTOINCREMENT,inv_no TEXT,number TEXT,date TEXT NOT NULL,customer_id INTEGER,customer_name TEXT,total REAL DEFAULT 0,subtotal REAL DEFAULT 0,discount REAL DEFAULT 0,tax REAL DEFAULT 0,paid REAL DEFAULT 0,due REAL DEFAULT 0,payment_method TEXT DEFAULT \'كاش\',notes TEXT DEFAULT \'\')');
      await db.execute('CREATE TABLE invoice_items(id INTEGER PRIMARY KEY AUTOINCREMENT,invoice_id INTEGER NOT NULL,product_id INTEGER,qty REAL DEFAULT 1,quantity REAL DEFAULT 1,price REAL DEFAULT 0,discount REAL DEFAULT 0,total REAL DEFAULT 0,product_name TEXT DEFAULT \'\')');
      await db.execute('CREATE TABLE payments(id INTEGER PRIMARY KEY AUTOINCREMENT,invoice_id INTEGER,amount REAL DEFAULT 0,method TEXT,date TEXT)');
      await db.execute('CREATE INDEX IF NOT EXISTS idx_invoices_date ON invoices(date)');
      await db.execute('CREATE TABLE expenses(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT,amount REAL DEFAULT 0,date TEXT,category TEXT)');
      await db.execute('CREATE TABLE journal(id INTEGER PRIMARY KEY AUTOINCREMENT,date TEXT,account_debit TEXT,account_credit TEXT,amount REAL DEFAULT 0,description TEXT,ref_id INTEGER)');
      await db.execute('CREATE TABLE users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,role TEXT,username TEXT UNIQUE,password TEXT)');
      await db.insert('users', {'name':'مدير النظام','role':'مدير','username':'admin','password':'1234'});
    });
  }
  Future<List<Map<String,dynamic>>> query(String table,{String? where,List<Object?>? args}) async => (await database).query(table,where:where,whereArgs:args,orderBy:'id DESC');
  Future<List<Map<String,dynamic>>> all(String table,{String? where,List<Object?>? args}) => query(table,where:where,args:args);
  Future<int> insert(String table,Map<String,dynamic> data) async => (await database).insert(table,data);
  Future<int> update(String table,Map<String,dynamic> data,int id) async => (await database).update(table,data,where:'id=?',whereArgs:[id]);
  Future<int> delete(String table,int id) async => (await database).delete(table,where:'id=?',whereArgs:[id]);
  Future<num> scalar(String sql,[List<Object?> args=const[]]) async { final rows=await (await database).rawQuery(sql,args); return (rows.first.values.first as num?)??0; }
  Future<Map<String,num>> dashboard() async { final now=DateTime.now(); final start=DateTime(now.year,now.month,now.day).toIso8601String(); final sales=await scalar('SELECT COALESCE(SUM(total),0) FROM invoices WHERE date>=?',[start]); final allSales=await scalar('SELECT COALESCE(SUM(total),0) FROM invoices'); final expenses=await scalar('SELECT COALESCE(SUM(amount),0) FROM expenses'); return {'sales':sales,'profit':allSales-expenses,'products':await scalar('SELECT COUNT(*) FROM products'),'customers':await scalar('SELECT COUNT(*) FROM customers'),'invoices':await scalar('SELECT COUNT(*) FROM invoices')}; }
  Future<Map<String,num>> summary() => dashboard();
  Future<List<double>> monthlySales() => dailySales();
  Future<List<double>> chart() async { final result=<double>[]; final now=DateTime.now(); for(var i=5;i>=0;i--){final start=DateTime(now.year,now.month-i,1).toIso8601String();final end=DateTime(now.year,now.month-i+1,1).toIso8601String();result.add((await scalar('SELECT COALESCE(SUM(total),0) FROM invoices WHERE date>=? AND date<?',[start,end])).toDouble());}return result; }
  Future<void> recordSale({required String invoiceNo, int? customerId, required String customerName, required List<Map<String,dynamic>> items, required double discount, required String paymentMethod, required double paid, required String notes}) async { final db=await database; await db.transaction((txn) async { final subtotal=items.fold<double>(0,(sum,item)=>sum+((item['qty'] as num)* (item['price'] as num))); final tax=(subtotal-discount)*.15; final total=subtotal-discount+tax; final due=total-paid; final invoiceId=await txn.insert('invoices',{'inv_no':invoiceNo,'number':invoiceNo,'date':DateTime.now().toIso8601String(),'customer_id':customerId,'customer_name':customerName,'total':total,'subtotal':subtotal,'discount':discount,'tax':tax,'paid':paid,'due':due,'payment_method':paymentMethod,'notes':notes}); for(final item in items){await txn.insert('invoice_items',{'invoice_id':invoiceId,'product_id':item['product_id'],'product_name':item['name'],'qty':item['qty'],'quantity':item['qty'],'price':item['price'],'discount':item['discount']??0,'total':(item['qty'] as num)*(item['price'] as num)}); if(item['product_id']!=null){await txn.rawUpdate('UPDATE products SET quantity=quantity-? WHERE id=?',[item['qty'],item['product_id']]);}} await txn.insert('payments',{'invoice_id':invoiceId,'amount':paid,'method':paymentMethod,'date':DateTime.now().toIso8601String()}); await txn.insert('journal',{'date':DateTime.now().toIso8601String(),'account_debit':customerName=='نقدي'?paymentMethod:'العملاء','account_credit':'المبيعات','amount':total,'description':'بيع فاتورة $invoiceNo','ref_id':invoiceId}); await txn.insert('journal',{'date':DateTime.now().toIso8601String(),'account_debit':'تكلفة البضاعة','account_credit':'المخزون','amount':items.fold<double>(0,(s,i)=>s+((i['qty'] as num)*(i['cost'] as num? ?? 0))),'description':'تكلفة فاتورة $invoiceNo','ref_id':invoiceId}); }); }
  Future<void> addExpense(String title,double amount,String category) async { final db=await database; await db.transaction((txn) async { final id=await txn.insert('expenses',{'title':title,'amount':amount,'date':DateTime.now().toIso8601String(),'category':category}); await txn.insert('journal',{'date':DateTime.now().toIso8601String(),'account_debit':category,'account_credit':'الصندوق','amount':amount,'description':title,'ref_id':id}); }); }
  Future<List<Map<String,dynamic>>> journalRows() => all('journal');
  Future<List<double>> dailySales() async { final db=await database; final now=DateTime.now(); final out=<double>[]; for(var i=6;i>=0;i--){final s=DateTime(now.year,now.month,now.day-i);final e=s.add(const Duration(days:1));final rows=await db.rawQuery('SELECT COALESCE(SUM(total),0) v FROM invoices WHERE date>=? AND date<?',[s.toIso8601String(),e.toIso8601String()]);out.add((rows.first['v'] as num).toDouble());} return out; }
  Future<void> seedDemo() async { final db=await database; for(var i=1;i<=20;i++){await db.insert('products',{'name':'منتج تجريبي $i','barcode':'628000000${i.toString().padLeft(2,'0')}','price':i*12.5,'cost':i*8.0,'quantity':i*3,'type':i%4==0?'وزن': 'عادي','unit':i%4==0?'كجم':'قطعة'});} for(var i=1;i<=5;i++){await db.insert('customers',{'name':'عميل تجريبي $i','phone':'050000000$i','balance':0,'address':'الرياض'});} for(var i=1;i<=10;i++){final total=i*125.0;final id=await db.insert('invoices',{'inv_no':'DEMO-$i','date':DateTime.now().subtract(Duration(days:i)).toIso8601String(),'customer_id':i%5+1,'total':total,'discount':0,'tax':total*.15,'paid':total,'due':0,'payment_method':'كاش','notes':'بيانات تجريبية'});await db.insert('invoice_items',{'invoice_id':id,'product_id':i,'qty':1,'price':total,'discount':0,'total':total});} }
}
