import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../../core/database/database_helper.dart';
import '../../core/services/pdf_service.dart';

class NewInvoiceScreen extends StatefulWidget{const NewInvoiceScreen({super.key});@override State<NewInvoiceScreen> createState()=>_NewInvoiceState();}
class _NewInvoiceState extends State<NewInvoiceScreen>{final customer=TextEditingController();final amount=TextEditingController();String message='';Future<void> save({required bool print})async{final subtotal=double.tryParse(amount.text)??0;if(subtotal<=0){setState(()=>message='أدخل مبلغًا صحيحًا');return;}final tax=subtotal*.15;final number='INV-${DateFormat('yyyyMMddHHmmss').format(DateTime.now())}';await DatabaseHelper.instance.insert('invoices',{'number':number,'customer_name':customer.text,'subtotal':subtotal,'tax':tax,'total':subtotal+tax,'created_at':DateTime.now().toIso8601String()});if(print){await PdfService.printInvoice(number:number,customer:customer.text,subtotal:subtotal,tax:tax,total:subtotal+tax);}if(mounted){if(print){setState(()=>message='تم الحفظ وفتح شاشة الطباعة والمشاركة');}else{Navigator.pop(context);}}}
@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('فاتورة جديدة')),body:ListView(padding:const EdgeInsets.all(16),children:[TextField(controller:customer,decoration:const InputDecoration(labelText:'العميل',prefixIcon:Icon(Icons.person),border:OutlineInputBorder())),const SizedBox(height:12),OutlinedButton.icon(onPressed:()async{final rows=await DatabaseHelper.instance.all('products');if(!mounted)return;showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('الأصناف'),content:SizedBox(width:360,height:260,child:rows.isEmpty?const Center(child:Text('لا توجد أصناف')):ListView(children:rows.map((r)=>ListTile(title:Text(r['name']),subtitle:Text('${r['sale_price']} ر.س'),onTap:()=>Navigator.pop(context))).toList())));},icon:const Icon(Icons.add_box),label:const Text('إضافة صنف')),const SizedBox(height:12),TextField(controller:amount,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'المجموع قبل الضريبة',border:OutlineInputBorder())),const SizedBox(height:10),const Card(child:ListTile(title:Text('ضريبة القيمة المضافة'),trailing:Text('15%'))),const SizedBox(height:14),Row(children:[Expanded(child:FilledButton(onPressed:()=>save(print:false),child:const Text('حفظ'))),const SizedBox(width:8),Expanded(child:OutlinedButton.icon(onPressed:()=>save(print:true),icon:const Icon(Icons.print),label:const Text('حفظ وطباعة PDF')))]),if(message.isNotEmpty)Padding(padding:const EdgeInsets.only(top:14),child:Text(message,style:const TextStyle(color:Colors.green,fontWeight:FontWeight.bold))) ]));}
}
